services:
  - type: web
    name: alia-legal
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 600 app:app"
    autoDeploy: true
